# Generated by Django 3.1.5 on 2026-01-05 21:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Prenume')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nume')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon')),
                ('message', models.TextField(verbose_name='Mesaj')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False, verbose_name='Citit')),
            ],
            options={
                'verbose_name': 'Mesaj Contact',
                'verbose_name_plural': 'Mesaje Contact',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titlu')),
                ('description', models.TextField(verbose_name='Descriere')),
                ('image', models.ImageField(blank=True, null=True, upload_to='courses/', verbose_name='Imagine')),
                ('duration', models.CharField(max_length=50, verbose_name='Durată')),
                ('level', models.CharField(choices=[('incepator', 'Începător'), ('intermediar', 'Intermediar'), ('avansat', 'Avansat')], max_length=50, verbose_name='Nivel')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Activ')),
            ],
            options={
                'verbose_name': 'Curs',
                'verbose_name_plural': 'Cursuri',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True, verbose_name='Data înscrierii')),
                ('completed', models.BooleanField(default=False, verbose_name='Completat')),
                ('progress', models.IntegerField(default=0, verbose_name='Progress (%)')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='courses.course', verbose_name='Curs')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL, verbose_name='Utilizator')),
            ],
            options={
                'verbose_name': 'Înscriere',
                'verbose_name_plural': 'Înscrieri',
                'ordering': ['-enrolled_at'],
                'unique_together': {('user', 'course')},
            },
        ),
    ]
