# Generated by Django 3.1.5 on 2026-01-05 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titlu lecție')),
                ('video', models.FileField(upload_to='lessons/videos/', verbose_name='Video')),
                ('duration', models.CharField(blank=True, max_length=20, verbose_name='Durată')),
                ('order', models.PositiveIntegerField(verbose_name='Ordine')),
                ('is_free', models.BooleanField(default=False, verbose_name='Preview gratuit')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.course', verbose_name='Curs')),
            ],
            options={
                'verbose_name': 'Lecție',
                'verbose_name_plural': 'Lecții',
                'ordering': ['order'],
                'unique_together': {('course', 'order')},
            },
        ),
    ]
