# Generated by Django 3.1.5 on 2026-02-10 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_lessonprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='suport_curs',
            field=models.FileField(blank=True, null=True, upload_to='lessons/curricula/', verbose_name='Suport pentru curs'),
        ),
    ]
