# Generated by Django 4.2.27 on 2026-02-11 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_contactmessage_id_alter_course_id_and_more'),
        ('courses', '0005_lessonpr'),
    ]

    operations = [
    ]
