# Generated by Django 4.2.27 on 2026-02-11 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_merge_20260211_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonpr',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
